name: Push docker

on: 
    pull_request:
        branches:
            - main 
        types: [closed]

jobs:
    merged:
        runs-on: ubuntu-latest
        if: ${{ github.event.pull_request.merged }}
        steps:
            - name: Clone repo
              run:
                git clone $GITHUB_SERVER_URL/$GITHUB_REPOSITORY . 

            - name: Loge in dockerhub
              run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
            
            - name: Build image
              run: |
                docker build -t ${{ secrets.DOCKER_USERNAME }}/my-image:latest .
                docker tag ${{ secrets.DOCKER_USERNAME }}/my-image:latest ${{ secrets.DOCKER_USERNAME }}/my-image:${{ github.sha }}
            
            - name: Push image
              run: |
                docker push ${{ secrets.DOCKER_USERNAME }}/my-image:latest
                docker push ${{ secrets.DOCKER_USERNAME }}/my-image:${{ github.sha }}